"""add user_id to patient table

Revision ID: 1dd93c52c8a0
Revises: d7603bf090dc
Create Date: 2025-04-08 00:43:05.732916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '1dd93c52c8a0'
down_revision: Union[str, None] = 'd7603bf090dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('user_id', UUID(as_uuid=True), nullable=False, unique=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
