"""initial migration

Revision ID: e28e3012446e
Revises: 
Create Date: 2025-03-29 23:08:04.907214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid



# revision identifiers, used by Alembic.
revision: str = 'e28e3012446e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Create patients table."""
    op.create_table(
        "patients",
        sa.Column("id", sa.UUID(), primary_key=True, default=uuid.uuid4, nullable=False),
        sa.Column("first_name", sa.String(100), nullable=True),
        sa.Column("last_name", sa.String(100), nullable=True),
        sa.Column("email", sa.String(100), nullable=True, unique=True),
        sa.Column("username", sa.String(100), nullable=False, unique=True),
        sa.Column("phone_number", sa.String(100), nullable=True, unique=True),
        sa.Column("date_of_birth", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), default=True),
        sa.Column("date_created", sa.DateTime(), server_default=sa.func.now()),
        sa.Column("date_modified", sa.Date(), nullable=True),
    )



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
