"""creare user authentication table

Revision ID: 1d2e8ad3a6d3
Revises: 
Create Date: 2025-04-03 01:50:26.766220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '1d2e8ad3a6d3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'users',
        sa.Column('id', sa.UUID(as_uuid=True), primary_key=True, default=uuid.uuid4, nullable=False),
        sa.Column('role', sa.String(100), nullable=False, default='user'),
        sa.Column('username', sa.String(100), nullable=False, unique=True),
        sa.Column('hash_password', sa.String(100), nullable=False),
        sa.Column('date_created', sa.DateTime, server_default=sa.func.now()),
        sa.Column('date_modified', sa.Date, nullable=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
