"""Remove duration and add column appointment_end, alter column appointment_time to appointment_start

Revision ID: d8e8d4aabffa
Revises: eab3eae26b84
Create Date: 2025-04-01 13:23:10.584917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd8e8d4aabffa'
down_revision: Union[str, None] = 'eab3eae26b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """drop column."""
    op.drop_column('bookings', 'duration')
    
    """add column"""
    op.add_column('bookings', sa.Column('appointment_end', sa.Time(), nullable=False))
    
    """alter column name"""
    op.alter_column('bookings', 'appointment_time', new_column_name = 'appointment_start')



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
