"""add user_id to docter table , modify create_date and modified_date docter and docter specialization table

Revision ID: 71768937b1e6
Revises: 89c15a2c41ce
Create Date: 2025-04-08 01:14:21.661482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects.postgresql import UUID


# revision identifiers, used by Alembic.
revision: str = '71768937b1e6'
down_revision: Union[str, None] = '89c15a2c41ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('user_id', UUID(as_uuid=True), nullable=False, unique=True))
    
    op.alter_column('doctors', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('doctors', sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    
    op.alter_column('doctor_specializations', sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('doctor_specializations', sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
