"""update doctor table --> change specialization_id to be nullable

Revision ID: ed35067b8206
Revises: 71768937b1e6
Create Date: 2025-04-08 18:50:05.426355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'ed35067b8206'
down_revision: Union[str, None] = '71768937b1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "doctors",
        "specialization_id",
        existing_type=sa.UUID(as_uuid=True),
        nullable=True
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    
    # ### end Alembic commands ###
